# configs/default.yaml

SEED: 42
DATA_DIR: USTC-TFC2016_malware   # folder containing train_data.npy, train_labels.npy, test_data.npy, test_labels.npy
IMG_SHAPE: [40, 40, 1]
NUM_CLASSES: 9
LATENT_DIM: 100
EPOCHS: 2000
BATCH_SIZE: 256
VAL_FRACTION: 0.5
FID_CAP: 200

ARTIFACTS:
  checkpoints: artifacts/gan/checkpoints
  synthetic: artifacts/gan/synthetic
  summaries: artifacts/gan/summaries
  tensorboard: artifacts/tensorboard


